<?php
// Set doctype explicitly if it is not `HTML4_LOOSE`, i.e. 'HTML 4.01 Transitional'
$this->doctype('HTML5');

// Load translation data
$this->i18nTheme();

//HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries
$this->js(array(
    pi::url('static/js/html5shiv.js') => array(
        'conditional' => 'lt IE 9'
    ),
    pi::url('static/js/respond.min.js') => array(
        'conditional' => 'lt IE 9'
    ),
));

// Load jQuery
$this->jquery();

// Load Bootstrap css/js and font-awesome
$this->bootstrap(array(
    'js/bootstrap.min.js',
    'font-awesome/css/font-awesome.min.css'
));

// Load front.css
$this->css($this->assetTheme('css/front.css'));

// Load localization css
$this->css($this->assetLocale('locale.css'));

// Load front.js on footer
$this->footScript()->appendFile($this->assetTheme('js/front.js'));

// Apple icons
// Apple icon for iphone
$this->headLink(array(
    'rel'   => 'apple-touch-icon',
    'href'  => $this->assetTheme('image/touch-icon-iphone.png')
));
// Apple icon for ipad
$this->headLink(array(
    'rel'   => 'apple-touch-icon',
    'sizes' => '72x72',
    'href'  => $this->assetTheme('image/touch-icon-ipad.png')
));
// Apple icon for iphone retina
$this->headLink(array(
    'rel'   => 'apple-touch-icon',
    'sizes' => '114x114',
    'href'  => $this->assetTheme('image/touch-icon-iphone-retina.png')
));
// Apple icon for ipad retina
$this->headLink(array(
    'rel'   => 'apple-touch-icon',
    'sizes' => '114x114',
    'href'  => $this->assetTheme('image/touch-icon-ipad-retina.png')
));

// Meta Viewport Tag
$this->headMeta('width=device-width, initial-scale=1.0', 'viewport');

// Explicitly load favicon
$this->headLink(array(
    'rel'   => 'shortcut icon',
    'type'  => 'image/x-icon',
    'href'  => $this->favicon(),
));
$this->headLink(array(
    'rel'   => 'shortcut icon',
    'type'  => 'image/png',
    'href'  => $this->favicon('favicon.png'),
));

// Load google analytics code
$this->ga();

// Get module name
$module = Pi::service('module')->current();

// Get navigation
$navigation = $this->nav('front');

// Get block
$blocks = $this->blocks();
$blockTemplate = $this->template('block');

// Get breadcrumbs
$breadcrumbs = $this->breadcrumb(
    array('prefix' => array(
        array(
            'label' => __('Home'),
            'href' => Pi::url($this->url('home'))
        )
    ))
);
?>
<!DOCTYPE HTML>
<html lang="<?php echo $locale; ?>">
<head>
    <meta charset="<?php echo $charset; ?>">
    <!--[if IE]><meta http-equiv="X-UA-Compatible" content="IE=edge"><![endif]-->
</head>
<body id="pi-<?php echo $module; ?>" class="pi-locale-<?php echo $locale; ?>">
<!-- Header: brand, slogan, user bar -->
<header class="pi-header">
    <nav class="navbar navbar-inverse">
        <div class="container">
            <div class="row">
                <div class="col-md-12">
                    <div class="navbar-header">
                        <button class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                            <i class="fa fa-bars"></i>
                        </button>
                        <?php if ($module == 'system') { ?>
                            <h1 class="navbar-brand">
                                <a href="https://www.faragostaresh.com" title="<?php echo _escape($sitename); ?>">
                                    <?php echo _escape($sitename); ?>
                                </a>
                            </h1>
                        <?php } else { ?>
                            <h2 class="navbar-brand">
                                <a href="https://www.faragostaresh.com" title="<?php echo _escape($sitename); ?>">
                                    <?php echo _escape($sitename); ?>
                                </a>
                            </h2>
                        <?php } ?>
                    </div>
                    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                        <ul class="nav navbar-nav navbar-right">
                            <li><a title="وب سایت و نرم افزار تحت وب" href="<?php echo Pi::url($this->url('home')); ?>page/web"><i class="fa fa-desktop"></i> وب سایت و نرم افزار تحت وب</a></li>
                            <li><a title="نرم افزار تلفن همراه" href="<?php echo Pi::url($this->url('home')); ?>page/mobile"><i class="fa fa-mobile-phone"></i> نرم افزار تلفن همراه</a></li>
                            <li><a title="مشتریان" href="<?php echo Pi::url($this->url('home')); ?>portfolio"><i class="fa fa-barcode"></i> مشتریان</a></li>
                            <li><a title="پشتیبانی" href="<?php echo Pi::url($this->url('home')); ?>support"><i class="fa fa-ticket"></i> پشتیبانی</a></li>
                            <li><a title="درباره ما" href="<?php echo Pi::url($this->url('home')); ?>page/about"><i class="fa fa-quote-right"></i> درباره ما</a></li>
                            <li><a title="تماس با ما" href="<?php echo Pi::url($this->url('home')); ?>contact"><i class="fa fa-envelope"></i> تماس با ما</a></li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </nav>
    <?php if (!empty($blocks['0'])) { ?>
        <div class="pi-zone-0">
            <?php foreach ($blocks['0'] as $block) {
                include $blockTemplate;
            } ?>
        </div>
    <?php } ?>
</header>
<section class="pi-main-container">
    <div class="container">
        <?php if ($breadcrumbs) { echo $breadcrumbs; } ?>
        <!-- Flash messenger -->
        <?php include $this->template('flash-messenger'); ?>
        <div class="row">
            <!-- Left zone -->
            <?php if (!empty($blocks['1'])) { ?>
                <div class="pi-zone-1 col-md-4">
                    <?php foreach ($blocks['1'] as $block) {
                        include $blockTemplate;
                    } ?>
                </div>
            <?php } ?>
            <div class="<?php
            if (isset($blocks['1']) && isset($blocks['8'])) {
                echo 'col-md-4';
            } elseif (isset($blocks['1']) || isset($blocks['8'])) {
                echo 'col-md-8';
            } else {
                echo 'col-md-12';
            }
            ?>">
                <!-- Center top zone -->
                <?php if (isset($blocks['2'])) { ?>
                    <div class="pi-zone-2">
                        <?php foreach ($blocks['2'] as $block) {
                            include $blockTemplate;
                        } ?>
                    </div>
                <?php } ?>
                <?php if (isset($blocks['3']) || isset($blocks['4'])) { ?>
                    <div class="row">
                        <div class="col-md-6 pi-zone-3">
                            <?php
                            if (isset($blocks['3'])) {
                                foreach ($blocks['3'] as $block) {
                                    include $blockTemplate;
                                }
                            }
                            ?>
                        </div>
                        <div class="col-md-6 pi-zone-4">
                            <?php
                            if (isset($blocks['4'])) {
                                foreach ($blocks['4'] as $block) {
                                    include $blockTemplate;
                                }
                            }
                            ?>
                        </div>
                    </div>
                <?php } ?>

                <!-- Module content starts -->
                <?php if (!empty($content)) { ?>
                    <div class="<?php echo $module; ?>">
                        <div class="pi-module-content" ng-app="<?php echo $module; ?>">
                            <?php echo $content; ?>
                        </div>
                        <?php echo Pi::service('comment')->load(array('options' => array('type' => 'js'))); ?>
                    </div>
                <?php } ?>
                <!-- Module content ends -->

                <?php if (isset($blocks['5']) || isset($blocks['6'])) { ?>
                    <div class="row">
                        <div class="col-md-6 pi-zone-5">
                            <?php
                            if (isset($blocks['5'])) {
                                foreach ($blocks['5'] as $block) {
                                    include $blockTemplate;
                                }
                            }
                            ?>
                        </div>
                        <div class="col-md-6 pi-zone-6">
                            <?php
                            if (isset($blocks['6'])) {
                                foreach ($blocks['6'] as $block) {
                                    include $blockTemplate;
                                }
                            }
                            ?>
                        </div>
                    </div>
                <?php } ?>
                <!-- Center bottom zone -->
                <?php if (isset($blocks['7'])) { ?>
                    <div class="pi-zone-7">
                        <?php foreach ($blocks['7'] as $block) {
                            include $blockTemplate;
                        } ?>
                    </div>
                <?php } ?>
            </div>

            <!-- Right zone -->
            <?php if (isset($blocks['8'])) { ?>
                <div class="col-md-4 pi-zone-8">
                    <?php foreach ($blocks['8'] as $block) {
                        include $blockTemplate;
                    } ?>
                </div>
            <?php } ?>
        </div>
        <!-- Bottom foot zone -->
        <?php if (isset($blocks['99'])) { ?>
            <div class="pi-zone-99">
                <?php foreach ($blocks['99'] as $block) {
                    include $blockTemplate;
                } ?>
            </div>
        <?php } ?>
    </div>
</section>
<footer class="pi-footer">
    <div class="pi-footer-bar-1">
        <div class="container">
            <div class="row">
                <div class="col-md-2 col-sm-6 col-xs-12">
                    <div class="pi-footer-title">
                        <h5>گواهی نامه ها</h5>
                    </div>
                    <div class="pi-footer-content clearfix">
                        <div class="row">
                            <div class="col-xs-6">
                                <img class="img-responsive" alt='enamad' id='drftsguinbpexlaprgvl' style='cursor:pointer' onclick='window.open("https://trustseal.enamad.ir/Verify.aspx?id=10235&p=nbpddrfswkynfuixyncr", "Popup","toolbar=no, location=no, statusbar=no, menubar=no, scrollbars=1, resizable=0, width=580, height=600, top=30")' src='https://trustseal.enamad.ir/logo.aspx?id=10235&p=lznbgthvqesgvjymfujy'/>
                            </div>
                            <div class="col-xs-6">
                                <img class="img-responsive" alt='پرداخت آنلاین بانک ملت' src='<?php echo $this->assetTheme('image/behpardakht.png'); ?>'/>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="col-md-6 col-sm-6 col-xs-12">
                    <div class="pi-footer-title">
                        <h5><i class="fa fa-paper-clip"></i> فراگسترش</h5>
                    </div>
                    <div class="pi-footer-content">
                        <p>فراگسترش با بهره گیری از متخصصین مجرب در زمینه برنامه نویسی تحت وب و موبایل ، و همچنین شبکه و طراحی در سال ۱۳۸۶ کار خود را آغاز نمود . تمرکز اصلی فراگسترش بر روی توسعه و پیاده سازی وب سایت ، بر پایه سیستم های مدیریت محتوا متن باز و آزاد است . در همین حال به طور گسترده در توسعه نرم افزار های متن باز تحت وب و تلفن های همراه مشارکت دارد.</p>
                    </div>
                </div>
                <div class="col-md-2 col-sm-6 col-xs-6">
                    <ul class="list-unstyled">
                        <li><a title="طراحی و توسعه وب" href="<?php echo Pi::url($this->url('home')); ?>page/web">طراحی و توسعه وب</a></li>
                        <li><a title="نرم افزار تلفن همراه" href="<?php echo Pi::url($this->url('home')); ?>page/mobile">نرم افزار تلفن همراه</a></li>
                        <li><a title="مشتریان" href="<?php echo Pi::url($this->url('home')); ?>portfolio">مشتریان</a></li>
                        <li><a title="درباره ما" href="<?php echo Pi::url($this->url('home')); ?>page/about">درباره ما</a></li>
                        <li><a title="تماس با ما" href="<?php echo Pi::url($this->url('home')); ?>contact">تماس با ما</a></li>
                    </ul>
                </div>
                <div class="col-md-2 col-sm-6 col-xs-6">
                    <ul class="list-unstyled">
                        <li><a title="ثبت دامنه" href="<?php echo Pi::url($this->url('home')); ?>page/domain">ثبت دامنه</a></li>
                        <li><a title="میزبانی وب" href="<?php echo Pi::url($this->url('home')); ?>page/web-hosting">میزبانی وب</a></li>
                        <li><a title="بهینه سازی برای  موتورهای جستجو" href="<?php echo Pi::url($this->url('home')); ?>page/seo">بهینه سازی</a></li>
                        <li><a title="پشتیبانی فنی" href="<?php echo Pi::url($this->url('home')); ?>page/support">پشتیبانی فنی</a></li>
                        <li><a title="قوانین و مقررات" href="<?php echo Pi::url($this->url('home')); ?>page/terms-and-conditions">قوانین و مقررات</a></li>
                    </ul>
                </div>
            </div>
        </div>
    </div>
    <div class="pi-footer-bar-2">
        <div class="container">
            <div class="row">
                <div class="col-md-6 col-sm-12 col-xs-12 text-left">
                    <div class="pi-footer-copyright" rel="license">تمامی حقوق مادی و معنوی برای <a href="https://www.faragostaresh.com" title="فراگسترش">فراگسترش</a> محفوظ می باشد .</div>
                </div>
                <div class="col-md-6 col-sm-12 col-xs-12 text-right">
                    <div class="pi-footer-icon">
                        <ul class="list-inline">
                            <li><a title="sitemap" href="<?php echo Pi::url($this->url('home')); ?>sitemap.xml"><i class="fa fa-sitemap"></i></a></li>
                            <li><a target="_blank" rel="nofollow publisher" title="فراگسترش در گوگل پلاس" href="https://plus.google.com/u/2/103250253220257244537"><i class="fa fa-google-plus"></i></a></li>
                            <li><a target="_blank" rel="nofollow" title="فراگسترش در لینکداین" href="https://www.linkedin.com/company/faragostaresh"><i class="fa fa-linkedin"></i></a></li>
                            <li><a target="_blank" rel="nofollow" title="فراگسترش در گیت هاب" href="https://www.github.com/faragostaresh"><i class="fa fa-github"></i></a></li>
                            <li><a target="_blank" rel="nofollow" title="فراگسترش در تویتر" href="https://www.twitter.com/faragostaresh"><i class="fa fa-twitter"></i></a></li>
                            <li><a target="_blank" rel="nofollow" title="فراگسترش در فیسبوک" href="https://www.facebook.com/Faragostaresh"><i class="fa fa-facebook"></i></a></li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </div>
</footer>
</body>
</html>